pipeline {
  agent {
    docker { image 'node:16-alpine' }
  }
  stages {
    stage('Test') {
      steps {
        sh 'node --version'
      } }
    stage('Test1') {
      steps {
        echo "py --version"
      }
    }
  }

